---

- name: "{{ ansible_distribution }}: Chapter 3.2. All Packages"
  vars:
    msg: |
      Linux From Scratch - Latest Stable
      Chapter 3.2. All Packages
      http://www.linuxfromscratch.org/lfs/view/stable/chapter03/packages.html
  debug:
    msg: "{{ msg.split('\n') }}"

#- name: "{{ansible_distribution}}: get a list of the packages"
#  command: cat "{{lfs}}/package-list"
#  register: package_list
#
#- name: "{{ansible_distribution}}: show me the list of files"
#  debug: msg={{package_list.stdout_lines}}
