---

- name: "{{ ansible_distribution }}: Chapter 5.5. gcc pass 1"
  vars:
    msg: |
      Linux From Scratch - Latest Stable
      Chapter 5.5. gcc pass 1
      http://www.linuxfromscratch.org/lfs/view/stable/chapter05/gcc-pass1.html
  debug:
    msg: "{{ msg.split('\n') }}"

- name: "{{ ansible_distribution }}: install gcc_env.sh"
  copy:
    dest: /tmp/gcc_env.sh
    src: gcc_env.sh

- name: "{{ ansible_distribution }}: install gcc_pass1.sh"
  copy:
    dest: /tmp/gcc_pass1.sh
    src: gcc_pass1.sh

- name: "{{ ansible_distribution }}: run gcc_pass1.sh"
  become: true
  become_user: lfs
  shell: /tmp/gcc_pass1.sh
