---

- name: "{{ ansible_distribution }}: Chapter 5.7. Glibc"
  vars:
    msg: |
      Linux From Scratch - Latest Stable
      Chapter 5.7. Glibc
      http://www.linuxfromscratch.org/lfs/view/stable/chapter05/glibc.html
  debug:
    msg: "{{ msg.split('\n') }}"

- name: "{{ ansible_distribution }}: install glibc_env.sh"
  copy:
    dest: /tmp/glibc_env.sh
    src: glibc_env.sh

- name: "{{ ansible_distribution }}: install glibc.sh"
  copy:
    dest: /tmp/glibc.sh
    src: glibc.sh

- name: "{{ ansible_distribution }}: run glibc.sh"
  become: true
  become_user: lfs
  shell: /tmp/glibc.sh
